# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVbQPoXhQxYQ8GdnCNvSEdgo7uXAit_L
"""

from google.colab import files
uploaded = files.upload()  # Sube tu Libro2.xlsx

!pip install folium openpyxl -q

import pandas as pd
import numpy as np
import folium
from IPython.display import display, HTML
import ipywidgets as widgets
from ipywidgets import Output, VBox, HBox
import warnings
warnings.filterwarnings("ignore")

# Leer el Excel (los encabezados reales están en la fila 2)
df = pd.read_excel("Libro2.xlsx", header=1)

# Limpiar columnas
df.columns = df.columns.astype(str).str.strip()

# Eliminar filas completamente vacías
df = df.dropna(how="all")

# Quedarnos solo con filas que tengan PILOTO válido
df = df[df["PILOTO"].notna()].copy()
df["PILOTO"] = df["PILOTO"].astype(str).str.strip()

# Función para limpiar coordenadas (vienen con puntos/comas raras)
def limpiar_coord(x):
    if pd.isna(x):
        return np.nan
    x = str(x).replace(",", ".").strip()
    try:
        return float(x)
    except:
        return np.nan

def corregir_lat(x):
    if pd.isna(x):
        return np.nan
    if abs(x) > 90:
        x = x / 1_000_000
    return x

def corregir_lon(x):
    if pd.isna(x):
        return np.nan
    if abs(x) > 180:
        x = x / 1_000_000
    return x

df["LATITUD"] = df["LATITUD"].apply(limpiar_coord).apply(corregir_lat)
df["LONGUITUD"] = df["LONGUITUD"].apply(limpiar_coord).apply(corregir_lon)

# Limpiar ESTADO (quitar espacios raros)
df["ESTADO"] = df["ESTADO"].astype(str).str.strip().str.upper()

print(f"✅ Total de registros cargados: {len(df)}")
print(f"✅ Pilotos únicos: {df['PILOTO'].nunique()}")
print(f"✅ Estados disponibles: {df['ESTADO'].unique()}")

"""def buscar_por_piloto(codigo):
    '''Busca un piloto y devuelve un resumen + DataFrame de sus cámaras'''
    codigo = str(codigo).strip()
    resultado = df[df["PILOTO"] == codigo].copy()

    if resultado.empty:
        print(f"❌ No se encontró el piloto: {codigo}")
        return None

    total = len(resultado)
    lat = resultado["LATITUD"].dropna().iloc[0] if not resultado["LATITUD"].dropna().empty else None
    lon = resultado["LONGUITUD"].dropna().iloc[0] if not resultado["LONGUITUD"].dropna().empty else None
    estado = resultado["ESTADO"].iloc[0] if not resultado["ESTADO"].empty else "N/D"

    # Contar por estado
    conteo_estado = resultado["ESTADO"].value_counts().to_dict()

    print("=" * 60)
    print(f"📌  PILOTO: {codigo}")
    print("=" * 60)
    print(f"🎥  Cantidad de cámaras asociadas: {total}")
    print(f"📊  Detalle por estado: {conteo_estado}")
    print(f"📍  Latitud:  {lat}")
    print(f"📍  Longitud: {lon}")
    print("-" * 60)

    columnas = ["CAMARA", "TIPO", "ESTADO", "DIRECCION", "MARCA", "MODELO", "SECTOR"]
    columnas = [c for c in columnas if c in resultado.columns]
    print(resultado[columnas].to_string(index=False))
    print("=" * 60)

    return resultado, lat, lon, codigo
"""

def mostrar_mapa(lat, lon, codigo, resultado):
    """Muestra el mapa con marcadores y un botón a Google Maps"""
    if lat is None or lon is None or pd.isna(lat) or pd.isna(lon):
        print("⚠️ Este piloto no tiene coordenadas válidas para mostrar en el mapa.")
        return

    # Crear mapa base
    mapa = folium.Map(location=[lat, lon], zoom_start=17, tiles="OpenStreetMap")

    # Marcador con la ubicación del piloto
    popup_html = f"""
    <div style="font-family: Arial; font-size: 13px;">
        <b>PILOTO:</b> {codigo}<br>
        <b>Cámaras:</b> {len(resultado)}<br>
        <b>Estado:</b> {resultado['ESTADO'].iloc[0]}<br>
        <b>Lat:</b> {lat}<br>
        <b>Lon:</b> {lon}
    </div>
    """
    folium.Marker(
        [lat, lon],
        popup=folium.Popup(popup_html, max_width=300),
        tooltip=f"Piloto {codigo}",
        icon=folium.Icon(color="red", icon="camera", prefix="fa")
    ).add_to(mapa)

    display(mapa)

    # Botón "Abrir en Google Maps" (sin API Key, es solo un link)
    google_url = f"https://www.google.com/maps/search/?api=1&query={lat},{lon}"
    boton_html = f"""
    <a href="{google_url}" target="_blank" style="
        display:inline-block;
        padding:10px 18px;
        background-color:#1a73e8;
        color:white;
        border-radius:6px;
        text-decoration:none;
        font-family:Arial;
        font-weight:bold;
        margin-top:8px;">
        🗺️ Abrir en Google Maps
    </a>
    """
    display(HTML(boton_html))



from IPython.display import display, HTML

total = len(df)
funcionando = len(df[df["ESTADO"] == "FUNCIONANDO"])
no_funciona = len(df[df["ESTADO"] == "NO FUNCIONA"])
otros = total - funcionando - no_funciona
porcentaje = round((funcionando / total) * 100, 2) if total > 0 else 0

html_resumen = f"""
<div style="display:flex; gap:15px; font-family:Arial; margin:15px 0;">
    <div style="flex:1; background:#e8f5e9; padding:15px; border-radius:8px; border-left:5px solid #4caf50;">
        <h4 style="margin:0; color:#2e7d32;">✅ FUNCIONANDO</h4>
        <h2 style="margin:5px 0;">{funcionando}</h2>
    </div>
    <div style="flex:1; background:#ffebee; padding:15px; border-radius:8px; border-left:5px solid #f44336;">
        <h4 style="margin:0; color:#c62828;">❌ NO FUNCIONA</h4>
        <h2 style="margin:5px 0;">{no_funciona}</h2>
    </div>
    <div style="flex:1; background:#e3f2fd; padding:15px; border-radius:8px; border-left:5px solid #1a73e8;">
        <h4 style="margin:0; color:#0d47a1;">📹 TOTAL</h4>
        <h2 style="margin:5px 0;">{total}</h2>
    </div>
    <div style="flex:1; background:#fff8e1; padding:15px; border-radius:8px; border-left:5px solid #ffa000;">
        <h4 style="margin:0; color:#e65100;">📈 DISPONIBILIDAD</h4>
        <h2 style="margin:5px 0;">{porcentaje}%</h2>
    </div>
</div>
"""
display(HTML(html_resumen))